export const jobs = [
  {
    id: 1,
    title: 'Frontend Developer',
    company: 'TechCo Ltd',
    location: 'New York, NY',
    description: 'We are seeking a talented and experienced Web Developer to join our dynamic team. The ideal candidate should have a strong understanding of front-end and back-end web development technologies. You will be responsible for designing, coding, and modifying websites, from layout to function. If you are passionate about web development and have a keen eye for detail, we want to hear from you..',
    requirements: ['Bachelor\'s degree in Computer Science or related field', 'Experience with React and JavaScript', 'Strong problem-solving skills'],
    qualifications: ['3+ years of frontend development experience', 'Excellent communication skills', 'Ability to work in a team'],
  },
  {
    id: 2,
    title: 'Backend Developer',
    company: 'CodeTech Inc',
    location: 'San Francisco, CA',
    description: `We are hiring Registered Nurses to provide high-quality patient care in our healthcare facility. The ideal candidates should be compassionate, detail-oriented, and dedicated to improving patients' lives. You will be responsible for assessing patient health, administering medications, and collaborating with the medical team to develop care plans.`,
    requirements: ['Bachelor\'s degree in Computer Engineering', 'Proficiency in Node.js and MongoDB', 'Understanding of RESTful APIs'],
    qualifications: ['5+ years of backend development experience', 'Experience with cloud services like AWS', 'Agile development experience'],
  },
  {
    id: 3,
    title: 'UX/UI Designer',
    company: 'DesignMasters',
    location: 'Los Angeles, CA',
    description: 'Join our creative team as a UX/UI Designer and create amazing user experiences...',
    requirements: ['Bachelor\'s degree in Design or related field', 'Proficiency in Adobe Creative Suite', 'Strong portfolio of design work'],
    qualifications: ['2+ years of UX/UI design experience', 'Experience with user testing and research', 'Creative thinking and problem-solving skills'],
  },
  {
    id: 1,
    title: 'Marketing Lead',
    company: 'TechCo Ltd',
    location: 'New York, NY',
    description: 'We are seeking a talented and experienced Web Developer to join our dynamic team. The ideal candidate should have a strong understanding of front-end and back-end web development technologies. You will be responsible for designing, coding, and modifying websites, from layout to function. If you are passionate about web development and have a keen eye for detail, we want to hear from you..',
    requirements: ['Bachelor\'s degree in Computer Science or related field', 'Experience with React and JavaScript', 'Strong problem-solving skills'],
    qualifications: ['3+ years of frontend development experience', 'Excellent communication skills', 'Ability to work in a team'],
  },
  {
    id: 2,
    title: 'Customer executive',
    company: 'CodeTech Inc',
    location: 'San Francisco, CA',
    description: 'CodeTech Inc is seeking a talented Backend Developer...',
    requirements: ['Bachelor\'s degree in Computer Engineering', 'Proficiency in Node.js and MongoDB', 'Understanding of RESTful APIs'],
    qualifications: ['5+ years of backend development experience', 'Experience with cloud services like AWS', 'Agile development experience'],
  },
  {
    id: 3,
    title: 'UX/UI Designer',
    company: 'DesignMasters',
    location: 'Los Angeles, CA',
    description: `We are looking for a Marketing Manager to lead our marketing efforts and drive growth. The ideal candidate should have a strong background in digital marketing, including SEO, SEM, and social media marketing. You will be responsible for developing and executing marketing strategies to increase brand awareness and generate leads. If you are a creative and data-driven marketer, we'd love to have you on our team.`,
    requirements: ['Bachelor\'s degree in Design or related field', 'Proficiency in Adobe Creative Suite', 'Strong portfolio of design work'],
    qualifications: ['2+ years of UX/UI design experience', 'Experience with user testing and research', 'Creative thinking and problem-solving skills'],
  },
  {
    id: 1,
    title: 'Business Executive',
    company: 'TechCo Ltd',
    location: 'New York, NY',
    description: 'We are seeking a talented and experienced Web Developer to join our dynamic team. The ideal candidate should have a strong understanding of front-end and back-end web development technologies. You will be responsible for designing, coding, and modifying websites, from layout to function. If you are passionate about web development and have a keen eye for detail, we want to hear from you..',
    requirements: ['Bachelor\'s degree in Computer Science or related field', 'Experience with React and JavaScript', 'Strong problem-solving skills'],
    qualifications: ['3+ years of frontend development experience', 'Excellent communication skills', 'Ability to work in a team'],
  },
  {
    id: 2,
    title: 'Backend Developer',
    company: 'CodeTech Inc',
    location: 'San Francisco, CA',
    description: 'CodeTech Inc is seeking a talented Backend Developer...',
    requirements: ['Bachelor\'s degree in Computer Engineering', 'Proficiency in Node.js and MongoDB', 'Understanding of RESTful APIs'],
    qualifications: ['5+ years of backend development experience', 'Experience with cloud services like AWS', 'Agile development experience'],
  },
  {
    id: 3,
    title: 'UX/UI Designer',
    company: 'DesignMasters',
    location: 'Los Angeles, CA',
    description: 'Join our creative team as a UX/UI Designer and create amazing user experiences...',
    requirements: ['Bachelor\'s degree in Design or related field', 'Proficiency in Adobe Creative Suite', 'Strong portfolio of design work'],
    qualifications: ['2+ years of UX/UI design experience', 'Experience with user testing and research', 'Creative thinking and problem-solving skills'],
  },
  {
    id: 3,
    title: 'UX/UI Designer',
    company: 'DesignMasters',
    location: 'Los Angeles, CA',
    description: `We are looking for a Marketing Manager to lead our marketing efforts and drive growth. The ideal candidate should have a strong background in digital marketing, including SEO, SEM, and social media marketing. You will be responsible for developing and executing marketing strategies to increase brand awareness and generate leads. If you are a creative and data-driven marketer, we'd love to have you on our team.`,
    requirements: ['Bachelor\'s degree in Design or related field', 'Proficiency in Adobe Creative Suite', 'Strong portfolio of design work'],
    qualifications: ['2+ years of UX/UI design experience', 'Experience with user testing and research', 'Creative thinking and problem-solving skills'],
  },
  {
    id: 1,
    title: 'Business Executive',
    company: 'TechCo Ltd',
    location: 'New York, NY',
    description: 'We are seeking a talented and experienced Web Developer to join our dynamic team. The ideal candidate should have a strong understanding of front-end and back-end web development technologies. You will be responsible for designing, coding, and modifying websites, from layout to function. If you are passionate about web development and have a keen eye for detail, we want to hear from you..',
    requirements: ['Bachelor\'s degree in Computer Science or related field', 'Experience with React and JavaScript', 'Strong problem-solving skills'],
    qualifications: ['3+ years of frontend development experience', 'Excellent communication skills', 'Ability to work in a team'],
  },
  {
    id: 2,
    title: 'Backend Developer',
    company: 'CodeTech Inc',
    location: 'San Francisco, CA',
    description: 'CodeTech Inc is seeking a talented Backend Developer...',
    requirements: ['Bachelor\'s degree in Computer Engineering', 'Proficiency in Node.js and MongoDB', 'Understanding of RESTful APIs'],
    qualifications: ['5+ years of backend development experience', 'Experience with cloud services like AWS', 'Agile development experience'],
  },
  {
    id: 3,
    title: 'UX/UI Designer',
    company: 'DesignMasters',
    location: 'Los Angeles, CA',
    description: 'Join our creative team as a UX/UI Designer and create amazing user experiences...',
    requirements: ['Bachelor\'s degree in Design or related field', 'Proficiency in Adobe Creative Suite', 'Strong portfolio of design work'],
    qualifications: ['2+ years of UX/UI design experience', 'Experience with user testing and research', 'Creative thinking and problem-solving skills'],
  },
];
